name: Update Jobs List

on:
  schedule:
    - cron: "0 * * * *" # every hour (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 20 (has global fetch)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch latest jobs (Greenhouse + Lever)
        run: node fetch-jobs.mjs

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add jobs.json
          git commit -m "Auto-update jobs.json [hourly]" || echo "No changes"
          git push
