name: Update jobs.json

on:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours
  workflow_dispatch:        # allow manual run from Actions tab

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # Add real deps later (requests, feedparser, etc.)
          pip install requests

      - name: Generate jobs.json
        run: |
          python scripts/generate_jobs.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add jobs.json
            git commit -m "Auto-update jobs.json [skip ci]"
            git push
          else
            echo "No changes."
          fi
