name: Update jobs.json

on:
  schedule:
    - cron: "0 */3 * * *" # Every 3 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run job updater
        run: |
          python scripts/generate_jobs.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add jobs.json
          git commit -m "Auto-update jobs.json" || echo "No changes"
          git push

