name: Update jobs.json

on:
  schedule:
    - cron: "0 */1 * * *"   # every 3 hours
  workflow_dispatch:        # allow manual run

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate jobs.json
        run: |
          python scripts/generate_jobs.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add jobs.json
          git commit -m "Auto-update jobs.json [skip ci]" || echo "No changes"
          git push
